# Generated by Django 5.2.18 on 2026-10-08 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("perfil_id", models.CharField(max_length=40)),
                ("perfil_nombre", models.CharField(max_length=80)),
                ("perfil_descripcion", models.TextField(blank=True)),
                ("hp_max", models.PositiveSmallIntegerField()),
                ("hp", models.PositiveSmallIntegerField()),
                ("xp", models.PositiveIntegerField(default=0)),
                ("atributos", models.JSONField(default=dict)),
                ("puntos_atributo", models.PositiveSmallIntegerField(default=0)),
                ("puntuacion", models.PositiveIntegerField(default=0)),
                ("aciertos", models.PositiveSmallIntegerField(default=0)),
                ("decisiones", models.PositiveSmallIntegerField(default=0)),
                ("temas", models.JSONField(default=list)),
                ("secuencia", models.JSONField(default=list)),
                ("indice", models.PositiveSmallIntegerField(default=0)),
                ("semilla", models.BigIntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("completada", "Completada"),
                            ("derrota", "Derrota (sin vidas)"),
                        ],
                        default="en_curso",
                        max_length=12,
                    ),
                ),
                ("logros", models.JSONField(default=list)),
                ("resultado_pendiente", models.JSONField(blank=True, null=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creada"],
            },
        ),
        migrations.CreateModel(
            name="RegistroDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                ("evento_id", models.CharField(max_length=60)),
                ("evento_titulo", models.CharField(max_length=120)),
                ("tema_id", models.CharField(max_length=60)),
                ("subtema_nombre", models.CharField(max_length=120)),
                ("tipo", models.CharField(max_length=15)),
                ("opcion_id", models.CharField(max_length=10)),
                ("opcion_texto", models.TextField()),
                ("correcta", models.BooleanField()),
                (
                    "probabilidad",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("tirada", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "partida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="app.partida",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partida", "orden"), name="decision_unica_por_orden"
                    )
                ],
            },
        ),
    ]
